### ISSUE TITLE
Test for non-host-relative paths.

### ISSUE THREAD

**Issue by Zegnat** [aaronpk/webmention.rocks#28]
This is, in part, why @sebsel [failed to find my endpoint](https://seblog.nl/2017/01/18/2/day-3-relative-urls). [Discovery Test #3](https://webmention.rocks/test/3) & [#5](https://webmention.rocks/test/5) are described as using relative paths, but they only use paths relative to the host (starting with `/`) rather then truly relative to the current page.

My endpoint and URL work as follows:

```html
<link rel="canonical" href="http://vanderven.se/martijn/">
<link rel="webmention" href="mention.php">
```

This should resolve to `http://vanderven.se/martijn/mention.php`. Implementations could currently resolve this to `http://vanderven.se/mention.php` without failing a single <i>Webmention Rocks!</i>-test. This could be solved by having tests mirroring the current relative paths but using just `href="webmention"`.

(Maybe there should also be a test using [`<base>`](https://html.spec.whatwg.org/multipage/semantics.html#the-base-element)? I am not sure how many edge-cases for URL discovery you would want to cover.)

**Comment by aaronpk** [comment]
It sounds like this problem is not just a matter of resolving a URL relative to a path, but it's resolving a URL after having been redirected to another page. I've added a new test for path-relative URL resolution anyway.

**Comment by aaronpk** [comment]
https://webmention.rocks/test/22

**Comment by aaronpk** [comment]
It works! 

https://webmention.rocks/test/23

**Comment by aaronpk** [comment]
@sebsel can you try on test 23? It should cover the example of @Zegnat's site now!

**Comment by sebsel** [comment]
Will do! Note that the test-list on the front page has this test as /test/23, which probably should be /test/23/page, right?

**Comment by aaronpk** [comment]
Nope! You need to start at `/test/23`. It's tricky.

**Comment by sebsel** [comment]
I'm afraid I'm failing.
https://seblog.nl/2017/01/27/4/test

Here's my log:
```
[
  {
    "url": "https:\/\/webmention.rocks\/test\/23\/page",
    "endpoint": "https:\/\/webmention.rocks\/test\/23\/page\/page\/webmention\/MOfAbqNKpPOrUJE9ncmh",
    "code": 404,
    "location": null,
    "archive": false
  }
]
```

But it seems like my problem, right?

**Comment by aaronpk** [comment]
yep, looks like there's a problem with your relative URL resolution! Notice that the endpoint you found has `page/page` in it.

**Comment by sebsel** [comment]
Hm, I am confused. I got the following parts:
```
endpoint:  page/webmention/6KKlDhpgSfkF74trS0Nv
page:      https://webmention.rocks/test/23/page/wBcvtr9Cb6pCTiCcs5Jt
result:    https://webmention.rocks/test/23/page/page/webmention/6KKlDhpgSfkF74trS0Nv
```
Even doing the math manually, I think I am right: remove `wBc(...)`, add `page/wm/6KK(...)` to the end, then I get a double /page/. So then the question is: does the test work?

I add `endpoint` to `page`, after the redirect. The test still works relative to the page **before** redirect. I think the test is wrong there.

**Comment by aaronpk** [comment]
oh my gosh you're right. I got the logic flipped around in my head. Here's what should happen:

```
curl -I https://webmention.rocks/test/23/page
-> Location: page/cHSEGpBH7hyQetOinILl

curl -I https://webmention.rocks/test/23/page/cHSEGpBH7hyQetOinILl
-> Link: <webmention/L2zCg9FgxJTGFzzv6NM0>; rel=webmention

curl -X POST -d source=... https://webmention.rocks/test/23/page/webmention/L2zCg9FgxJTGFzzv6NM0
```

Note that in the last step, you need to resolve the relative part `webmention/L2zCg9FgxJTGFzzv6NM0` from the second URL rather than from the URL you linked to `https://webmention.rocks/test/23/page`

I just pushed a change for that so try again.

**Comment by sebsel** [comment]
Yaay! I passed now without rewriting anything myself :D

For reference, in my code:
```
    $response = remote::get($url);
    $url      = $response->info['url'];
```
Where `$info = curl_getinfo($curl);`, somewhere it the [toolkit](https://github.com/getkirby/toolkit) I use.

**Comment by aaronpk** [comment]
@sebsel glad that works now. Just to clarify, you already made a change to fix sending a webmention to @Zegnat right? You just didn't need to change anything again to pass this test? I just want to make sure this test is addressing the original problem as pointed out by @Zegnat's site.

**Comment by sebsel** [comment]
Yep, I did not change a thing for this test and I pass both test 23 and @Zegnat site! Not only `http://vanderven.se/martijn/` but also `http://vanderven.se/martijn`, which redirects to the first one, with a relative `"endpoint.php"` on it. I believe test 23 is addressing the same problem.
