### ISSUE TITLE
When doing verification, provide an Accept header preferring text/html

### ISSUE THREAD

**Issue by gobengo** [aaronpk/webmention.rocks#30]
I tried to implement far enough to pass [the first test](https://webmention.rocks/test/1). I *think* I should be, but am not. I could be wrong, but need your advice.

Here is my document https://distbin.com/activities/fbe90aeb-71ce-461c-852d-eeccd57f1cef

Notably, distbin responds with JSON if you don't provide a request header preferring to 'Accept: text/html'.

When it tries to webmention the test, it gets a 400 Bad Request Response. See:

```bash
⚡ curl "https://webmention.rocks/test/1/webmention?head=true" -XPOST -d "source=https://distbin.com/activities/fbe90aeb-71ce-461c-852d-eeccd57f1cef" -d "target=https://webmention.rocks/test/1" -v
*   Trying 173.230.155.197...
* Connected to webmention.rocks (173.230.155.197) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: webmention.rocks
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> POST /test/1/webmention?head=true HTTP/1.1
> Host: webmention.rocks
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 113
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 113 out of 113 bytes
< HTTP/1.1 400 Bad Request
< Server: nginx/1.10.2
< Date: Sat, 11 Mar 2017 13:44:42 GMT
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 181
< Connection: keep-alive
< 
no_link_found

The source document does not contain a link to the target URL.

The source document must contain an <a> tag with an href attribute matching the target URL specified.
```

However, the HTML representation of that URL actually does have at least one link whose href attribute matches.

```bash
⚡ curl "https://distbin.com/activities/fbe90aeb-71ce-461c-852d-eeccd57f1cef" -H "Accept: text/html" | grep "href=\"https://webmention.rocks/test/1"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8552    0  8552    0     0   2237      0 --:--:--  0:00:03 --:--:--  2236
      <main><a href="https://webmention.rocks/test/1">https://webmention.rocks/test/1</a></main>
            <a href="https://webmention.rocks/test/1">permalink</a>
```

I think maybe that the tests are not specifying an Accept header in a request, and is processing the response assuming the body will be Content-Type text/html. Maybe [this](https://github.com/aaronpk/webmention.rocks/blob/4820c4c3c3970c0032e5633263d97c576c3b729c/controllers/Webmention.php#L176) is the line?

@aaronpk Am I diagnosing this right?

**Comment by aaronpk** [comment]
You're right, the test suite should be including an Accept header, since the spec recommends it!
