### ISSUE TITLE
IndieAuth fails due to "invalid state"

### ISSUE THREAD

**Issue by tscs37** [aaronpk/webmention.rocks#32]
When the authentication workflow returns to the webmention.rocks webpage on Receiver Test 1, the page displays an "Invalid State" error;

>The state parameter provided did not match the state at the start of authorization. You will need to start the login process again.

This is incorrect, the state parameter is correctly supplied on my side with the parameter "state=<number>". My application is not modifying the state parameter in any way.

The problem probably lies in [controllers/AuthController.php#L100-L123](https://github.com/aaronpk/webmention.rocks/blob/master/controllers/AuthController.php#L100-L123)

The error in this section might require some cleaning up.

The incoming redirect to my page is:

```
/@mp/auth?me=https%3A%2F%2Fdev.qat7.com%2F%40tscs37&redirect_uri=https%3A%2F%2Fwebmention.rocks%2Fauth%2Fcallback&client_id=https%3A%2F%2Fwebmention.rocks%2F&state=9797849&response_type=id
```

The redirect to webmention.rocks is:

```
https://webmention.rocks/auth/callback?code=89lj0h3kmtrh3k2og7vpdtjk78dfkfio&me=https%3A%2F%2Fdev.qat7.com%2F%40tscs37&state=9797849
```

No further notable requests occur on my side.

(Please note that dev.qat7.com is a development instance and therefore rarely online or functional)

**Comment by aaronpk** [comment]
Do you have any browser extensions that block cookies? webmention.rocks will be trying to set a cookie in order to persist state between requests.

**Comment by tscs37** [comment]
I have Browser Extensions which Block 3rd Party cookies but I have not observed any blocking during this workflow so this should not be a problem, to be sure I disabled all plugins that relate to blocking, the error persists so far.

**Comment by aaronpk** [comment]
I just replaced the login mechanism of this site completely. Please let me know if you continue to have trouble logging in.

**Comment by tscs37** [comment]
Looks like it's fixed on my end, no further issues.
