### ISSUE TITLE
Updates for HTTP/2

### ISSUE THREAD

**Issue by Ryuno-Ki** [aaronpk/webmention.rocks#39]
Originally filled in https://github.com/curl/curl/issues/3877

I'm currently updating the Python library webmention-tools.
Therefore I'm running through the test cases and noticed something for [Test no 7](https://webmention.rocks/test/7).

As @bagder explained in the curl issue, all names are lowercased.
Do we need an update for the test suite?

**Comment by aaronpk** [comment]
This means your code is working as intended. The test case only makes sense for HTTP 1.0/1.1, but as soon as you fetch it with HTTP 2 there are no longer case-sensitive header names.
