### ISSUE TITLE
webmention references in some tests missing?

### ISSUE THREAD

**Issue by devongarde** [aaronpk/webmention.rocks#40]
I'm not sure if it's me not understanding the spec, or whether there's an issue with the tests, but a good number of them seem to be missing their rel="webmention" (or whatever) links. For example, tests 1 & 2. Other tests appear fine. 

I looked at them in various browsers, & downloaded them with curl, just in case it was some bizarre browser artifact, but got a consistent confusion.

Apologies in advance if this is me not understanding the tests.

I attach a zip of the test files I downloaded (using windows curl), just in case it's an artifact that only appears in certain circumstances.

[rocks.zip](https://github.com/aaronpk/webmention.rocks/files/3293844/rocks.zip)

**Comment by aaronpk** [comment]
That's the point of the test! ;-)

Try checking the HTTP headers.

**Comment by devongarde** [comment]
There's no link rel="webmention" in some of the headers, such as test 1 which says there is in the text! I've uploaded what I downloaded.

Ok, I've obviously misunderstood what's meant to be happening. Apologies for wasting your time. :-(

**Comment by aaronpk** [comment]
I don't see any example in your comment above. Here's what test 1 returns in the HTTP headers:

```
HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Sun, 16 Jun 2019 05:13:58 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Link: </test/1/webmention>; rel=webmention
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST
```

**Comment by devongarde** [comment]
You're right, I failed to post the HTML page I downloaded, so have now posted a zip of them all.

I'm clearly attempt to dig up the reference up the wrong way. I wasn't looking at the HTTP headers, just the HTML. Thanks for responding. I'll go work this out.

**Comment by devongarde** [comment]
Sorry for wasting your time.

**Comment by aaronpk** [comment]
no problem! Glad you figured it out!
