### ISSUE TITLE
Source URL is doubled

### ISSUE THREAD

**Issue by gkuznik** [aaronpk/webmention.rocks#51]
The source link used on webmention.rocks is wrong for all tests.
I use jekyll-webmention_io and made a test post. 
I verified with a proxy that the source URL sent is only https://grabriel.co/2024/03/02/webmention-test/, but on e.g. https://webmention.rocks/test/2 this shows as https://grabriel.co/2024/03/02/webmention-test/grabriel.co/2024/03/02/webmention-test/.

**Comment by aaronpk** [comment]
I just tried re-sending the webmentions from your page to the test site and now it works fine. I'm guessing at some point when you were testing, the markup on your site was wrong and was causing the microformats parser to double up the URL. Probably if it was missing the `https` from the link. For example, if your markup was:

```
<a href="grabriel.co/2024/03/02/other-webmention/">
```

Then the parser would treat that as a relative URL from `https://grabriel.co/2024/03/02/other-webmention/` and you'd end up with the doubled up URL `https://grabriel.co/2024/03/02/other-webmention/grabriel.co/2024/03/02/other-webmention/`.

Remember that what you see on webmention.rocks is the parsed microformats of your source page, not the URL you send in the webmention POST request.

**Comment by gkuznik** [comment]
Oh, makes sense, I'll look out for that, thanks.
