### ISSUE TITLE
delete/1 test is not parsing meta http-equiv

### ISSUE THREAD

**Issue by bear** [aaronpk/webmention.rocks#7]
I have implemented for my static site the sending of `410 GONE` via `<meta http-equiv="Status" content="410 GONE" />` but the second stage of delete/1 fails as webmention.rocks returns a 400 status code.

you can test against my deleted post: https://bear.im/bearlog/2016/123/testing-delete

**Comment by aaronpk** [comment]
@bear This was fixed on May 3, can you double check that it works for you?

**Comment by bear** [comment]
oops - yes, it does work

**Comment by aaronpk** [comment]
Thanks! I think you opened this issue on May 2, I must have just quickly fixed it and forgotten to update the issue!

**Comment by bear** [comment]
and to compound the lag, I checked your fix almost immediately but then forgot about the issue being open - d'oh!
